######################################################################
# Author: Iuliia Likhacheva, Bryanna Moreno Casas
# Username: likhachevai, morenocasasb
#
# Assignment: T11: The Legend of Tuna: Breath of Catnip
#
# Purpose: Learn about classes, inheritance, and Pygame
######################################################################
# Acknowledgements:
#
# Inspired by Zelda, rebuilt into Python by: https://github.com/clear-code-projects/Zelda
# Art generated by Stable Diffusion: https://stablediffusionweb.com/app/image-generator
# Borrowed some ideas from: https://realpython.com/pygame-a-primer/

# licensed under a Creative Commons
# Attribution-Noncommercial-Share Alike 3.0 United States License.
####################################################################################
import pygame, random


class NPC(pygame.sprite.Sprite):
    move_distance = 10

    def __init__(self, screen_size):
        """
        Handle the common logic: screen size, rect position, direction logic

        :param screen_size: size of the window, for ensuring the NPC stays on screen
        """
        super().__init__()
        self.screen_size = screen_size
        self.rect = pygame.Rect(0, 0, 0, 0) # Placeholder until child class sets up
        self.path = None #Child class or get_direction sets this

    def get_direction(self):
        """
        Keeps the Good NPC on the screen.

        :return: None
        """
        if self.rect.bottom >= self.screen_size[1]:
            # Bottom
            self.path = "north"
        if self.rect.top <= 0:
            # Top
            self.path = "south"
        if self.rect.left <= 0:
            # Left
            self.path = "east"
        if self.rect.right >= self.screen_size[0]:
            # Right
            self.path = "west"
        elif random.random() > .95:
            # Randomly change direction 5% of the time
            self.path = random.choice(self.directions)


class GoodNPC(NPC):
    directions = ['north', 'east', 'south', 'west']

    def __init__(self, screen_size):
        super().__init__(screen_size)
        self.surf = pygame.image.load('images/tacocat.png').convert_alpha()
        self.surf.set_colorkey((255, 255, 255), pygame.RLEACCEL)
        self.rect = self.surf.get_rect()
        self.rect.move_ip(screen_size[0] // 4, screen_size[1] // 4)
        self.path = random.choice(self.directions)


    def movement(self):
        """
        Moves the Good NPC around.

        :return: None
        """
        if self.path == "north":
            self.rect.move_ip(0, -self.move_distance)
        elif self.path == "south":
            self.rect.move_ip(0, self.move_distance)
        if self.path == "east":
            self.rect.move_ip(self.move_distance, 0)
        if self.path == "west":
            self.rect.move_ip(-self.move_distance, 0)

        self.get_direction()


class BadNPC(NPC):
    def __init__(self, screen_size):
        super().__init__(screen_size)
        self.surf = pygame.image.load('images/whiskers.png').convert_alpha()
        self.surf.set_colorkey((255, 255, 255), pygame.RLEACCEL)
        self.rect = self.surf.get_rect()
        self.rect.move_ip(screen_size[0] // 4, screen_size[1] // 4)
        self.horizontal_direction = 1  # start moving right
        self.vertical_step = 20 # pixels to move vertically when reaching edge

    def movement(self):
        self.rect.move_ip(self.horizontal_direction * self.move_distance, 0)
        if self.rect.right >= self.screen_size[0]:
            self.rect.right = self.screen_size[0]
            self.horizontal_direction = -1
        elif self.rect.left <= 0:
            self.rect.left = 0
            self.rect.move_ip(0, self.vertical_step)
            self.horizontal_direction = 1